# Numpy Tutorials
NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python

# What is an array
An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type

In [1]:
import numpy as np

In [3]:
lst = [1,2,3,4]
arr = np.array(lst)

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr.shape

(4,)

In [7]:
lst1 = [1,2,3,4,5]
lst2 = [2,3,4,5,6]
lst3 = [3,4,5,6,7]
arr1 = np.array([lst1,lst2,lst3])

In [9]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [8]:
arr1.shape# 3rows 5 columns

(3, 5)

In [10]:
arr

array([1, 2, 3, 4])

In [11]:
# indexing 
arr[3]

4

In [12]:
arr[3]=5

In [15]:
arr[:-1]

array([1, 2, 3])

In [16]:
arr[::-1]

array([5, 3, 2, 1])

In [17]:
arr[::-2]

array([5, 2])

In [18]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [26]:
arr1[2,4]

7

In [27]:
arr1[1:,1:3]

array([[3, 4],
       [4, 5]])

In [28]:
arr1[1:,3:]

array([[5, 6],
       [6, 7]])

In [31]:
arr1[:,3:].shape

(3, 2)

In [41]:
arr1[:,0:-1]

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [42]:
## EDA
arr

array([1, 2, 3, 5])

In [44]:
arr[arr<2]

array([1])

In [46]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [47]:
arr1.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 3, 4],
       [5, 6, 7]])

In [52]:
## to create an array mehanism
np.arange(1,20,2).reshape(2,5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [53]:
np.arange(1,20,2).reshape(1,10,1)

array([[[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9],
        [11],
        [13],
        [15],
        [17],
        [19]]])

In [54]:
arr * arr

array([ 1,  4,  9, 25])

In [59]:
arr1 * arr1

array([[ 1,  4,  9, 16, 25],
       [ 4,  9, 16, 25, 36],
       [ 9, 16, 25, 36, 49]])

In [60]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [61]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [66]:
np.random.randint(10,50,4).reshape(2,2)

array([[26, 47],
       [14, 46]])

In [67]:
np.random.randn(5,6)

array([[-0.3418066 ,  0.5729822 ,  1.53992082,  0.9546973 , -0.5095307 ,
        -0.67397055],
       [-1.27858266, -0.57602853,  1.18684133, -0.90037498, -0.17820957,
         0.75984895],
       [-0.382329  , -0.04754286,  2.613376  ,  0.89893803, -0.21628861,
        -0.53940165],
       [-0.65761684, -0.37120285,  0.54501849, -0.15589595, -1.20201583,
         0.60440771],
       [ 0.3505029 ,  1.51608882,  0.37378409,  0.26979638,  0.41128915,
         0.76749693]])

In [71]:
 np.random.random_sample((4,7))

array([[0.75373024, 0.69291941, 0.82562377, 0.38507009, 0.84432894,
        0.58576504, 0.24069274],
       [0.76827112, 0.45019132, 0.61893457, 0.93530342, 0.03199379,
        0.46668957, 0.41363865],
       [0.86455518, 0.28893939, 0.13304737, 0.63805127, 0.50569466,
        0.27274728, 0.35564295],
       [0.89893126, 0.50250967, 0.9297549 , 0.23749808, 0.18823184,
        0.01741489, 0.6104964 ]])