## Python Pandas Tutorials- Part 1
In Part we are going to learn about

* Pandas Dataframe
* Pandas Series
* Pandas Basic Operations

In [4]:
import pandas as pd
import numpy as np

In [6]:
np.arange(0,20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [11]:
# Create Dataframe
df = pd.DataFrame(data=np.arange(0,20).reshape(5,4),index=["Row1","Row2","Row3","Row4","Row5"],columns=['C1','C2','C3','C4'])

In [12]:
df.head()

C1  C2  C3  C4
Row1   0   1   2   3
Row2   4   5   6   7
Row3   8   9  10  11
Row4  12  13  14  15
Row5  16  17  18  19

In [13]:
df.tail()

C1  C2  C3  C4
Row1   0   1   2   3
Row2   4   5   6   7
Row3   8   9  10  11
Row4  12  13  14  15
Row5  16  17  18  19

In [14]:
type(df)

pandas.core.frame.DataFrame

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Row1 to Row5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C1      5 non-null      int32
 1   C2      5 non-null      int32
 2   C3      5 non-null      int32
 3   C4      5 non-null      int32
dtypes: int32(4)
memory usage: 120.0+ bytes


In [16]:
df.describe()

C1         C2         C3         C4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [17]:
## Indexing
## columnname,rowindex[loc],rowindex columnindex number[iloc]
df.head()

C1  C2  C3  C4
Row1   0   1   2   3
Row2   4   5   6   7
Row3   8   9  10  11
Row4  12  13  14  15
Row5  16  17  18  19

In [18]:
# Columnname
df[['C1','C2','C3']]

C1  C2  C3
Row1   0   1   2
Row2   4   5   6
Row3   8   9  10
Row4  12  13  14
Row5  16  17  18

In [21]:
# rowindex name[loc]
df.loc[['Row1','Row2']]

C1  C2  C3  C4
Row1   0   1   2   3
Row2   4   5   6   7

In [22]:
df.head()

C1  C2  C3  C4
Row1   0   1   2   3
Row2   4   5   6   7
Row3   8   9  10  11
Row4  12  13  14  15
Row5  16  17  18  19

In [23]:
# rowindex column index[iloc]
df.iloc[2:4,0:2]

C1  C2
Row3   8   9
Row4  12  13

In [26]:
df.iloc[2:,1:4]

C2  C3  C4
Row3   9  10  11
Row4  13  14  15
Row5  17  18  19

In [34]:
df.iloc[0:,0:4:3]

C1  C4
Row1   0   3
Row2   4   7
Row3   8  11
Row4  12  15
Row5  16  19

In [39]:
df.iloc[:,1:].values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

## Operations

In [41]:
df.isnull().sum()

C1    0
C2    0
C3    0
C4    0
dtype: int64

In [44]:
# Create Dataframe
df = pd.DataFrame(data=[[1,np.nan,2],[1,3,4]],index=["Row1","Row2"],columns=['C1','C2','C3'])

In [45]:
df

C1   C2  C3
Row1   1  NaN   2
Row2   1  3.0   4

In [46]:
df.isnull().sum()

C1    0
C2    1
C3    0
dtype: int64

In [50]:
df.isnull().sum()==0

C1     True
C2    False
C3     True
dtype: bool

In [53]:
df['C3'].value_counts()

2    1
4    1
Name: C3, dtype: int64

In [54]:
df['C3'].unique()

array([2, 4], dtype=int64)